### PR TITLE
Remove the build time jar dependency installation and embedded the jars instead

### PR DESCRIPTION
**Pull request by purbon**
Clean up jar dependencies code and so we end embedded dependencies the same gem. To do so I introduced a common code to load jars so we aim to simplify the management of jars in the long run.

Version 0.1.5 bump

### CODE REVIEW

**Comment by wiibaa** [comment]
@purbon me again with a most-probably-stupid question, the jar_manager is in the devutils gem but this gem is only a development dependency, so it will not ship in the packaged gem, no ?

**Comment by purbon** [comment]
@wiibaa is actually a very good point, I need to fix this.

**Comment by electrical** [comment]
Why is it in devutils in the first place if its such an important part of the plugin to function? :-)

**Comment by purbon** [comment]
I should not be there I agree.

**Comment by purbon** [comment]
my bad

**Comment by wiibaa** [comment]
pulling the sheet back towards me, with https://github.com/elastic/logstash/pull/1301/files LogStash::environment would have this jar loading feature, maybe need a minor rework

**Comment by purbon** [comment]
@wiibaa yes, I agree should go someplace there. Again I apologize for this stupid misplacement of the code.

**Comment by purbon** [comment]
Amended, I will make sure to add a proper jar manager within the core logstash as basis for this. So people can use it to load any kind of jars the need within their libs.

Again, @wiibaa thanks for the other pair of eyes, I appreciate the review.

**Comment by wiibaa** [comment]
@purbon :beers:

**Comment by purbon** [comment]
:beers: :beers: :beers:

**Comment by ph** [comment]
this ticket has a :beer: issue.

**Comment by jsvd** [comment]
why not bears instead! :bear: 
LGTM

**Pull request closed without merging**
