### PR TITLE
Make usage of the new stop semantics to properly shutdown the plugin

### LINKED ISSUE #10: refactor shutdown sequence to use plugin.stop
Change shutdown sequence to be triggered by plugin.stop instead of ShutdownSignal exception.
Also remove any calls to: shutdown, finished, finished?, running? or terminating?
This depends on https://github.com/elastic/logstash/pull/3895

### PR DESCRIPTION
**Pull request by purbon**
Implements `stop` to return from `run` according to https://github.com/elastic/logstash/issues/3210

Depends on https://github.com/elastic/logstash-devutils/pull/32 and https://github.com/elastic/logstash/pull/3812

Fixes #10

### CODE REVIEW

**Comment by andrewvc** [comment]
The changes make sense but the tests don't pass for me:

```
~/p/logstash-input-drupal_dblog (purbon-feature/use_new_stop) $ bundle exec rspec spec
uri:classloader:/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
F

Failures:

  1) LogStash::Inputs::DrupalDblog behaves like an interruptible input plugin #stop returns from run
     Failure/Error: expect(plugin_thread).to be_alive
       expected `#<Thread:0x48f5bde6 dead>.alive?` to return true, got false
     Shared Example Group: "an interruptible input plugin" called from ./spec/inputs/drupal_dblog_spec.rb:5
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-expectations-3.1.2/lib/rspec/expectations/fail_with.rb:30:in `fail_with'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-expectations-3.1.2/lib/rspec/expectations/handler.rb:37:in `handle_failure'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-expectations-3.1.2/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-expectations-3.1.2/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/logstash-devutils-0.0.16-java/lib/logstash/devutils/rspec/shared_examples.rb:14:in `block in (root)'
     # org/jruby/RubyBasicObject.java:1673:in `instance_exec'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:152:in `block in run'
     # org/jruby/RubyProc.java:308:in `call'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-wait-0.0.7/lib/rspec/wait.rb:46:in `block in (root)'
     # org/jruby/RubyBasicObject.java:1673:in `instance_exec'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:322:in `instance_exec'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:380:in `execute_with'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:446:in `block in run'
     # org/jruby/RubyProc.java:308:in `call'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:222:in `call'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:445:in `run'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/hooks.rb:500:in `run'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:331:in `with_around_example_hooks'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example.rb:149:in `run'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:490:in `block in run_examples'
     # org/jruby/RubyArray.java:2300:in `map'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:486:in `run_examples'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:453:in `run'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `block in run'
     # org/jruby/RubyArray.java:2300:in `map'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `block in run'
     # org/jruby/RubyArray.java:2300:in `map'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:454:in `run'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # org/jruby/RubyArray.java:2300:in `map'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:111:in `block in run_specs'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/reporter.rb:53:in `report'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:107:in `run_specs'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:85:in `run'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/lib/ruby/gems/shared/gems/rspec-core-3.1.7/exe/rspec:4:in `<top>'
     # org/jruby/RubyKernel.java:958:in `load'
     # /Users/andrewvc/.rbenv/versions/jruby-9.0.0.0/bin/rspec:23:in `<top>'
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```

**Comment by purbon** [comment]
@andrewvc I run the test again, but for me all is green. could you provide me with the seed used? probably this might help reproducing.

```
purbon-elastic% bundle exec rspec
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.

Finished in 1.13 seconds (files took 2.01 seconds to load)
1 example, 0 failures

Randomized with seed 26257

purbon-elastic% bundle exec rspec spec
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.

Finished in 1.09 seconds (files took 1.6 seconds to load)
1 example, 0 failures

Randomized with seed 47667 
```

have you tried running them again ? do they fail always?

**Comment by purbon** [comment]
@andrewvc why do you run then in ```jruby-9.0.0.0``` ? I run this test with the actual jruby used in core, .22, can you try with it?

**Comment by purbon** [comment]
@andrewvc are you sure you update your ```Gemfile``` to point to your ```logstash``` and ``devutils```? your error is most likely because of this.

**Comment by andrewvc** [comment]
LGTM! Just make sure you rebase to pull in @ph 's gemspec changes :)

**Pull request closed without merging**
